import { IconCategory, IconName } from "@/types/types";
import {
  BarChart2,
  Users,
  X,
  Briefcase,
  ClipboardList,
  MoreHorizontal,
  FileText,
  Search,
  Plus,
  Trash2,
  Edit,
  BarChart,
  Zap,
  Coffee,
  Mail,
  Bell,
  Calendar,
  Scissors,
  Headphones,
  Map,
  Flag,
  Database,
  Book,
  Code,
  CheckCircle2,
  AlertCircle,
  Info,
  Globe,
  Settings,
  ShieldCheck,
  Lock,
  Unlock,
  Loader2,
  Download,
  Upload,
  Image,
  Video,
  Star,
  Home,
  Menu,
  Moon,
  Sun,
  Eye,
  EyeOff,
  type LucideIcon,
} from "lucide-react";

export const iconComponents: Record<string, LucideIcon> = {
  BarChart2,
  BarChart,
  Users,
  Briefcase,
  ClipboardList,
  FileText,
  Search,
  Plus,
  X,
  MoreHorizontal,
  Trash2,
  Edit,
  Zap,
  Coffee,
  Mail,
  Bell,
  Calendar,
  Scissors,
  Headphones,
  Map,
  Flag,
  Database,
  Book,
  Code,
  CheckCircle2,
  AlertCircle,
  Info,
  Globe,
  Settings,
  ShieldCheck,
  Lock,
  Unlock,
  Loader2,
  Download,
  Upload,
  Image,
  Video,
  Star,
  Home,
  Menu,
  Moon,
  Sun,
  Eye,
  EyeOff,
};

export const getIconByName = (name: IconName): LucideIcon => {
  return iconComponents[name] || BarChart2;
};

export const renderIcon = (iconName: IconName, className = "h-5 w-5") => {
  const IconComponent = getIconByName(iconName);
  return <IconComponent className={className} />;
};

export const iconCategories: IconCategory[] = [
  {
    name: "Charts",
    icons: ["BarChart", "BarChart2"],
  },
  {
    name: "People",
    icons: ["Users"],
  },
  {
    name: "Business",
    icons: ["Briefcase", "ClipboardList", "FileText"],
  },
  {
    name: "Actions",
    icons: ["Search", "Plus", "X", "MoreHorizontal", "Trash2", "Edit", "Download", "Upload", "Loader2"],
  },
  {
    name: "Status & Alerts",
    icons: ["CheckCircle2", "AlertCircle", "Info", "ShieldCheck"],
  },
  {
    name: "Interface",
    icons: ["Menu", "Home", "Settings", "Eye", "EyeOff", "Lock", "Unlock"],
  },
  {
    name: "Media",
    icons: ["Image", "Video", "Star"],
  },
  {
    name: "Theme",
    icons: ["Moon", "Sun"],
  },
  {
    name: "Misc",
    icons: [
      "Zap",
      "Coffee",
      "Mail",
      "Bell",
      "Calendar",
      "Scissors",
      "Headphones",
      "Map",
      "Flag",
      "Database",
      "Book",
      "Code",
      "Globe",
    ],
  },
];

